### ISSUE TITLE
TODO: Series Markdown Pages

### ISSUE THREAD

**Issue by MrDogeBro** [Carberra/website#1]
This is the list of all the series markdown pages which need to be created.

### Series Name - Link

- [x] Building a discord.py bot (2019) [Superceded] - https://www.youtube.com/playlist?list=PLYeOw6sTSy6bHr2w8nOV0CpKskuOuU1XE
- [x] Building a Python Twitch bot (2020) [Outdated] - https://www.youtube.com/playlist?list=PLYeOw6sTSy6ZFDkfO9Kl8d37H_3wLyNxO
- [x] Building a discord.py but (2020) - https://www.youtube.com/playlist?list=PLYeOw6sTSy6ZGyygcbta7GcpI8a5-Cooc
- [x] Building a discord.py music bot (2020) - https://www.youtube.com/playlist?list=PLYeOw6sTSy6ZIfraPiUsJWuxjqoL47U3u
- [x] How to Python - https://www.youtube.com/playlist?list=PLYeOw6sTSy6bHRFwzIA3VAy05J2tJAAoS
- [x] Image manipulation with Python & Pillow (2021) - https://www.youtube.com/playlist?list=PLYeOw6sTSy6YViQG4Yiqu85t6w9ZFWJrP
- [x] Data analysis and visualization in Python (2021) - https://www.youtube.com/playlist?list=PLYeOw6sTSy6YTWAOpdMWLYGa2r3lvM5w2
- [x] Perfect Python - https://www.youtube.com/playlist?list=PLYeOw6sTSy6YZyg-8dtLl98q9wUA0QOVa
- [x] Python but Faster - https://www.youtube.com/playlist?list=PLYeOw6sTSy6ZotfqL7E6ePi4zX8vhEqKf

### Other Unknown

These are series which I did not know if they should be included or not so they are listed here so you can decide if they should be added or not.

- [x] Game development with Pygame (2021) [Cancelled] - https://www.youtube.com/watch?v=oEUdCMJTF3s&list=PLYeOw6sTSy6YoYZL4ZiyELHRvQlk5YI-2
- [x] Python is Awesome - https://www.youtube.com/playlist?list=PLYeOw6sTSy6aJ8ZlA4vGvgGVo42IhF-Pc
- [x] Visual Studio Code - https://www.youtube.com/playlist?list=PLYeOw6sTSy6YWgd1F1mLCmzgxOkxUuxeQ
- [x] Hikari supplementary tutorials - https://www.youtube.com/playlist?list=PLYeOw6sTSy6bavdLzROgQl6PAVuLh-xhE
